
# Point Blank Configuration

[combat]
	# Damage multiplier for all firearms
	damage_multiplier = 1.2
	# Recoil multiplier
	recoil_multiplier = 1.0

[server]
	# Whether players can craft guns (set to false if using the Black Market economy)
	allow_gun_crafting = true
	# Whether guns require ammo
	require_ammo = true
